#!/opt/lastlist/apps/python/venv/bin/python
from __future__ import print_function

from parse_mail import mail_parse
import sys
import logging
from logging.handlers import RotatingFileHandler

h = RotatingFileHandler('/opt/lastlist/1.0.0/bin/src/SendGrid-Mailer/logs/mailIn.log',
                        maxBytes=100000000, backupCount=12)
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logger.addHandler(h)


class SendGrid():
    def __init__(self, hostname='localhost'):
        self.hostname = hostname

    def send_mail(self, parsed_mail):
        logger.debug(parsed_mail)


data = []
try:
    for line in sys.stdin:
        data.append(line)
    print("data")
    print(data)

    sg = SendGrid()
    emailMsg = ''.join(data)
    pm = mail_parse(emailMsg)
    logger.debug(pm)
    sg.send_mail(emailMsg)


except Exception as exp:
    print(exp.message)
    logger.exception( exp )
